---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_component_registry_meta. Do not edit by hand.
-- Source of truth: `DefineComponent.Foo = { ... }` assignments throughout the project.
-- Declares the `Components` registry class and adds `---@field` entries so
-- editors autocomplete `Components.Foo`.

---@class Components
---@field CharacterComponent string
---@field ContactComponent string
---@field EnemyHealthComponent string
---@field PlayerComponent string
Components = {}
