---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_entity_registry_meta. Do not edit by hand.
-- Source of truth: `DefineEntity.Foo = { ... }` assignments throughout the project.
-- Declares the `Entities` registry class and adds `---@field` entries so
-- editors autocomplete `Entities.Foo`.

---@class Entities
---@field camera string
---@field dynamic_box string
---@field dynamic_circle string
---@field enemy string
---@field player string
---@field static_box string
---@field static_circle string
---@field trigger_box string
---@field trigger_circle string
Entities = {}
