---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_scene_registry_meta. Do not edit by hand.
-- Source of truth: `DefineScene.Foo = { ... }` assignments throughout the project.
-- Declares the `Scenes` registry class and adds `---@field` entries so
-- editors autocomplete `Scenes.Foo`.

---@class Scenes
---@field arena string
---@field arena_empty string
Scenes = {}
