---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_shader_params_meta. Do not edit by hand.
-- Source of truth: the SPIR-V reflection of each shader's `Material` cbuffer.
-- One class per shader lists its settable params (and texture bindings). Annotate a
-- DefineMaterial assignment to get autocomplete + type checks for that shader's params:
--   ---@type MaterialParams.outline
--   DefineMaterial.white_outline = { shader = Shaders.outline, outline_color = Color.white() }

---@class MaterialParams.distort
---@field shader? Shader
---@field tint? Color
---@field alpha_threshold? number
---@field distort_strength? number
---@field distort_speed? number
---@field textures? MaterialTextures.distort

---@class MaterialTextures.distort
---@field distort_tex? Texture|string

---@class MaterialParams.outline
---@field shader? Shader
---@field tint? Color
---@field outline_color? Color
---@field outline_width? number
---@field alpha_threshold? number

---@class MaterialParams.psychedelic
---@field shader? Shader
---@field tint? Color
---@field alpha_threshold? number

---@class MaterialParams.sprite
---@field shader? Shader
---@field tint? Color
---@field alpha_threshold? number

