DefineScene.Arena = {
    entities = {
        { prefab = Entities.Camera, pose_overrides = { position = Vector2(0, 0) }
        },

        { prefab = Entities.Player, pose_overrides = { position = Vector2(0, 0) },
        },

        { prefab = Entities.Enemy, pose_overrides = { position = Vector2(0, 4), rotation_deg = -90 } },
        { prefab = Entities.Enemy, pose_overrides = { position = Vector2(-4, 0) } },
        {
            prefab = Entities.Enemy,
            pose_overrides = { position = Vector2(4, 0), rotation_deg = 180 },
            cpp_overrides = { sprite = { material = Materials.CyanOutline } }
        },

        -- Perimeter walls
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-18, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-18, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-16, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-16, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-14, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-14, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-12, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-12, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-10, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-10, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-8, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-8, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-6, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-6, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-4, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-4, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-2, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-2, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(0, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(0, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(2, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(2, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(4, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(4, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(6, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(6, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(8, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(8, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(10, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(10, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(12, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(12, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(14, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(14, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(16, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(16, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(18, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(18, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, 12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, -12), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, -10), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, -10), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, -8), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, -8), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, -6), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, -6), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, -4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, -4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, -2), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, -2), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, 0), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, 0), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, 2), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, 2), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, 4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, 4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, 6), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, 6), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, 8), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, 8), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-20, 10), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(20, 10), scale = Vector2(2, 2) } },

        -- Interior crates: two cover lines
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-6, 4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-6, -4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-4, 4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(-4, -4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(4, 4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(4, -4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(6, 4), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticBox,     pose_overrides = { position = Vector2(6, -4), scale = Vector2(2, 2) } },

        -- Corner pillars
        { prefab = Entities.StaticCircle,  pose_overrides = { position = Vector2(-14, 8), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticCircle,  pose_overrides = { position = Vector2(14, 8), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticCircle,  pose_overrides = { position = Vector2(-14, -8), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticCircle,  pose_overrides = { position = Vector2(14, -8), scale = Vector2(2, 2) } },

        -- Mid-line pillars
        { prefab = Entities.StaticCircle,  pose_overrides = { position = Vector2(-10, 0), scale = Vector2(2, 2) } },
        { prefab = Entities.StaticCircle,  pose_overrides = { position = Vector2(10, 0), scale = Vector2(2, 2) } },

        -- Checkpoint triggers
        { prefab = Entities.TriggerCircle, pose_overrides = { position = Vector2(0, 8), scale = Vector2(2, 2) } },
        { prefab = Entities.TriggerCircle, pose_overrides = { position = Vector2(0, -8), scale = Vector2(2, 2) } },
    },
}
